[package]
name = "cross_site_request_forgery_csrf"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
actix-session = { version = "0.8", features = ["cookie-session"] }
serde = { version = "1.0", features = ["derive"] }
tera = "1"
rand = "0.8"
base64 = "0.21"
